using static ILOG.CPLEX.Cplex;

namespace ILOG.CPLEX
{
    class CplexHelper
    {
        public static Status MakeStatus(int var0, bool var1, bool var2)
        {
            switch (var0)
            {
                case 0:
                    return Status.Unknown;
                case 1:
                case 5:
                case 102:
                case 129:
                case 130:
                case 301:
                case 305:
                    return Status.Optimal;
                case 2:
                case 133:
                case 304:
                    return Status.Unbounded;
                case 3:
                case 15:
                case 17:
                case 19:
                case 31:
                case 302:
                    return Status.Infeasible;
                case 4:
                case 303:
                    return Status.InfeasibleOrUnbounded;
                case 6:
                case 14:
                case 16:
                case 18:
                case 32:
                case 33:
                case 34:
                case 35:
                case 36:
                case 37:
                case 38:
                case 39:
                case 306:
                    return Status.Unknown;
                case 10:
                case 11:
                case 13:
                case 21:
                case 22:
                case 25:
                case 106:
                case 110:
                case 112:
                case 117:
                case 126:
                    if (var1 && var2)
                    {
                        return Status.Optimal;
                    }
                    else if (var1)
                    {
                        return Status.Feasible;
                    }
                    else
                    {
                        if (var2)
                        {
                            return Status.Bounded;
                        }

                        return Status.Unknown;
                    }
                case 20:
                default:
                    return Status.Error;
                case 23:
                case 104:
                case 105:
                case 109:
                case 111:
                case 116:
                case 128:
                    if (var2)
                    {
                        return Status.Optimal;
                    }

                    return Status.Feasible;
                case 24:
                    if (var1)
                    {
                        return Status.Feasible;
                    }

                    return Status.Unknown;
                case 30:
                    return Status.Feasible;
            }
        }

        public static CplexStatus GetStatus(int var0)
        {
            switch (var0)
            {
                case 0:
                    return CplexStatus.Unknown;
                case 1:
                    return CplexStatus.Optimal;
                case 2:
                    return CplexStatus.Unbounded;
                case 3:
                    return CplexStatus.Infeasible;
                case 4:
                    return CplexStatus.InfOrUnbd;
                case 5:
                    return CplexStatus.OptimalInfeas;
                case 6:
                    return CplexStatus.NumBest;
                case 7:
                case 8:
                case 9:
                case 26:
                case 27:
                case 28:
                case 29:
                case 40:
                case 42:
                case 43:
                case 44:
                case 45:
                case 46:
                case 47:
                case 48:
                case 49:
                case 50:
                case 51:
                case 52:
                case 53:
                case 54:
                case 55:
                case 56:
                case 57:
                case 58:
                case 59:
                case 60:
                case 61:
                case 62:
                case 63:
                case 64:
                case 65:
                case 66:
                case 67:
                case 68:
                case 69:
                case 70:
                case 71:
                case 72:
                case 73:
                case 74:
                case 75:
                case 76:
                case 77:
                case 78:
                case 79:
                case 80:
                case 81:
                case 82:
                case 83:
                case 84:
                case 85:
                case 86:
                case 87:
                case 88:
                case 89:
                case 90:
                case 91:
                case 92:
                case 93:
                case 94:
                case 95:
                case 96:
                case 97:
                case 98:
                case 99:
                case 100:
                case 134:
                case 135:
                case 136:
                case 137:
                case 138:
                case 139:
                case 140:
                case 141:
                case 142:
                case 143:
                case 144:
                case 145:
                case 146:
                case 147:
                case 148:
                case 149:
                case 150:
                case 151:
                case 152:
                case 153:
                case 154:
                case 155:
                case 156:
                case 157:
                case 158:
                case 159:
                case 160:
                case 161:
                case 162:
                case 163:
                case 164:
                case 165:
                case 166:
                case 167:
                case 168:
                case 169:
                case 170:
                case 171:
                case 172:
                case 173:
                case 174:
                case 175:
                case 176:
                case 177:
                case 178:
                case 179:
                case 180:
                case 181:
                case 182:
                case 183:
                case 184:
                case 185:
                case 186:
                case 187:
                case 188:
                case 189:
                case 190:
                case 191:
                case 192:
                case 193:
                case 194:
                case 195:
                case 196:
                case 197:
                case 198:
                case 199:
                case 200:
                case 201:
                case 202:
                case 203:
                case 204:
                case 205:
                case 206:
                case 207:
                case 208:
                case 209:
                case 210:
                case 211:
                case 212:
                case 213:
                case 214:
                case 215:
                case 216:
                case 217:
                case 218:
                case 219:
                case 220:
                case 221:
                case 222:
                case 223:
                case 224:
                case 225:
                case 226:
                case 227:
                case 228:
                case 229:
                case 230:
                case 231:
                case 232:
                case 233:
                case 234:
                case 235:
                case 236:
                case 237:
                case 238:
                case 239:
                case 240:
                case 241:
                case 242:
                case 243:
                case 244:
                case 245:
                case 246:
                case 247:
                case 248:
                case 249:
                case 250:
                case 251:
                case 252:
                case 253:
                case 254:
                case 255:
                case 256:
                case 257:
                case 258:
                case 259:
                case 260:
                case 261:
                case 262:
                case 263:
                case 264:
                case 265:
                case 266:
                case 267:
                case 268:
                case 269:
                case 270:
                case 271:
                case 272:
                case 273:
                case 274:
                case 275:
                case 276:
                case 277:
                case 278:
                case 279:
                case 280:
                case 281:
                case 282:
                case 283:
                case 284:
                case 285:
                case 286:
                case 287:
                case 288:
                case 289:
                case 290:
                case 291:
                case 292:
                case 293:
                case 294:
                case 295:
                case 296:
                case 297:
                case 298:
                case 299:
                case 300:
                default:
                    return CplexStatus.Unknown;
                case 10:
                    return CplexStatus.AbortItLim;
                case 11:
                    return CplexStatus.AbortTimeLim;
                case 12:
                    return CplexStatus.AbortObjLim;
                case 13:
                    return CplexStatus.AbortUser;
                case 14:
                    return CplexStatus.FeasibleRelaxedSum;
                case 15:
                    return CplexStatus.OptimalRelaxedSum;
                case 16:
                    return CplexStatus.FeasibleRelaxedInf;
                case 17:
                    return CplexStatus.OptimalRelaxedInf;
                case 18:
                    return CplexStatus.FeasibleRelaxedQuad;
                case 19:
                    return CplexStatus.OptimalRelaxedQuad;
                case 20:
                    return CplexStatus.OptimalFaceUnbounded;
                case 21:
                    return CplexStatus.AbortPrimObjLim;
                case 22:
                    return CplexStatus.AbortDualObjLim;
                case 23:
                    return CplexStatus.Feasible;
                case 24:
                    return CplexStatus.FirstOrder;
                case 25:
                    return CplexStatus.AbortDetTimeLim;
                case 30:
                    return CplexStatus.ConflictFeasible;
                case 31:
                    return CplexStatus.ConflictMinimal;
                case 32:
                    return CplexStatus.ConflictAbortContradiction;
                case 33:
                    return CplexStatus.ConflictAbortTimeLim;
                case 34:
                    return CplexStatus.ConflictAbortItLim;
                case 35:
                    return CplexStatus.ConflictAbortNodeLim;
                case 36:
                    return CplexStatus.ConflictAbortObjLim;
                case 37:
                    return CplexStatus.ConflictAbortMemLim;
                case 38:
                    return CplexStatus.ConflictAbortUser;
                case 39:
                    return CplexStatus.ConflictAbortDetTimeLim;
                case 41:
                    return CplexStatus.NumBest;
                case 101:
                    return CplexStatus.Optimal;
                case 102:
                    return CplexStatus.OptimalTol;
                case 103:
                    return CplexStatus.Infeasible;
                case 104:
                    return CplexStatus.SolLim;
                case 105:
                    return CplexStatus.NodeLimFeas;
                case 106:
                    return CplexStatus.NodeLimInfeas;
                case 107:
                    return CplexStatus.AbortTimeLim;
                case 108:
                    return CplexStatus.AbortTimeLim;
                case 109:
                    return CplexStatus.FailFeas;
                case 110:
                    return CplexStatus.FailInfeas;
                case 111:
                    return CplexStatus.MemLimFeas;
                case 112:
                    return CplexStatus.MemLimInfeas;
                case 113:
                    return CplexStatus.AbortUser;
                case 114:
                    return CplexStatus.AbortUser;
                case 115:
                    return CplexStatus.OptimalInfeas;
                case 116:
                    return CplexStatus.FailFeasNoTree;
                case 117:
                    return CplexStatus.FailInfeasNoTree;
                case 118:
                    return CplexStatus.Unbounded;
                case 119:
                    return CplexStatus.InfOrUnbd;
                case 120:
                    return CplexStatus.FeasibleRelaxedSum;
                case 121:
                    return CplexStatus.OptimalRelaxedSum;
                case 122:
                    return CplexStatus.FeasibleRelaxedInf;
                case 123:
                    return CplexStatus.OptimalRelaxedInf;
                case 124:
                    return CplexStatus.FeasibleRelaxedQuad;
                case 125:
                    return CplexStatus.OptimalRelaxedQuad;
                case 126:
                    return CplexStatus.AbortRelaxed;
                case 127:
                    return CplexStatus.Feasible;
                case 128:
                    return CplexStatus.PopulateSolLim;
                case 129:
                    return CplexStatus.OptimalPopulated;
                case 130:
                    return CplexStatus.OptimalPopulatedTol;
                case 131:
                    return CplexStatus.AbortDetTimeLim;
                case 132:
                    return CplexStatus.AbortDetTimeLim;
                case 133:
                    return CplexStatus.RelaxationUnbounded;
                case 301:
                    return CplexStatus.MultiObjOptimal;
                case 302:
                    return CplexStatus.MultiObjInfeasible;
                case 303:
                    return CplexStatus.MultiObjInfOrUnbd;
                case 304:
                    return CplexStatus.MultiObjUnbounded;
                case 305:
                    return CplexStatus.MultiObjNonOptimal;
                case 306:
                    return CplexStatus.MultiObjStopped;
            }
        }
    }
}
